#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2025 Microsoft Corporation
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.

function usage() {
    echo "Sample script for extracting instructions and map data out of" >&2
    echo "autogenerated eBPF lskel headers" >&2
    echo "" >&2
    echo "USAGE: header_file field" >&2
    exit 1
}

ARGC=$#

EXPECTED_ARGS=2

if [ $ARGC -ne $EXPECTED_ARGS ] ; then
    usage
else
    printf $(gcc -E $1 | grep "static const char opts_$2" | \
		 awk -F"=" '{print $2}' | sed 's/[[:space:];]*$//' | sed 's/\"//g')
fi
